spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Course_DB  # Replace with your actual MongoDB URI
  messages:
    basename: messages # Reference to the custom messages.yml file

server:
  port: 8085
