spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Course_DB  # Replace with your actual MongoDB URI
  # webflux:
  #   base-path: /api

server:
  port: 8086  # Changed the port to 8081
